# Generated by Django 2.1.7 on 2021-05-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('VIN', models.CharField(max_length=120)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('exterior_color', models.TextField(blank=True, null=True)),
                ('interior', models.TextField(blank=True, null=True)),
                ('num_doors', models.IntegerField()),
                ('num_seats', models.IntegerField()),
                ('engine', models.CharField(max_length=120)),
                ('transmission', models.CharField(max_length=120)),
                ('wheels', models.CharField(max_length=120)),
                ('tires', models.CharField(max_length=120)),
                ('brakes', models.CharField(max_length=120)),
                ('steering_wheel', models.CharField(max_length=120)),
                ('sunroof', models.BooleanField()),
                ('convertible', models.BooleanField()),
                ('speedometer', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('horsepower', models.IntegerField()),
                ('audio_system', models.TextField()),
                ('cooling_system', models.BooleanField()),
                ('heating_system', models.BooleanField()),
            ],
        ),
    ]
