# Generated by Django 2.1.7 on 2021-05-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='audio_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brakes',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='convertible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='cooling_system',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='heating_system',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='horsepower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='num_doors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='num_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='speedometer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='steering_wheel',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sunroof',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tires',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='torque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='wheels',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
