# Generated by Django 2.1.7 on 2021-05-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210512_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='listing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
    ]
