# Generated by Django 2.1.7 on 2021-05-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='audio_system',
            field=models.TextField(blank=True, default='Stock', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brakes',
            field=models.CharField(blank=True, default='Disc', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='convertible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='cooling_system',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, default='V8 Inline-Six', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='exterior_color',
            field=models.TextField(blank=True, default='Black', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='heating_system',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='horsepower',
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='interior',
            field=models.TextField(blank=True, default='Beige', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='listing_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=50000, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='num_doors',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='num_seats',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='speedometer',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='steering_wheel',
            field=models.CharField(blank=True, default='3-spoke', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sunroof',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tires',
            field=models.CharField(blank=True, default='Firestone', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='torque',
            field=models.IntegerField(blank=True, default=250, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, default='Manual', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='wheels',
            field=models.CharField(blank=True, default='chrome wire', max_length=120, null=True),
        ),
    ]
