# Generated by Django 2.1.7 on 2021-05-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_auto_20210524_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.CharField(default='yearmakemodel', max_length=120, primary_key=True, serialize=False),
        ),
    ]
