# Generated by Django 2.1.7 on 2021-05-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_auto_20210524_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.CharField(default='<django.db.models.fields.IntegerField><django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=120, primary_key=True, serialize=False),
        ),
    ]
